### ISSUE TITLE
Remove auto-inference of attribute divisor

### ISSUE THREAD

**Issue by Pessimistress** [visgl/luma.gl#1044]
https://github.com/uber/luma.gl/blob/master/modules/webgl/src/classes/program-configuration.js#L108

See https://github.com/uber/deck.gl/pull/2919

**Comment by tsherif** [comment]
@Pessimistress This should be an easy fix. Any concerns about breakage elsewhere?

**Comment by ibgreen** [comment]
Worth running luma examples.

Updating title to be more specific: `Remove auto-inference of attribute types` => `Remove auto-inference of attribute divisor`.

At this stage I would only remove the divisor inference as it is a heuristic (as opposed to being based on a query of the compiled shader).
