### ISSUE TITLE
`luma.log.priority = 4` throws with WebGL1Context

### ISSUE THREAD

**Issue by Pessimistress** [visgl/luma.gl#1149]
Version: 7.1.0

Error:

```js
assert.js:5 Uncaught Error: Requires WebGL2
    at assert (assert.js:5)
    at assertWebGL2Context (webgl-checks.js:26)
    at Buffer.getData (buffer.js:203)
    at Buffer.getDebugData (buffer.js:283)
    at getDebugTableRow (debug-vertex-array.js:71)
    at getDebugTableForVertexArray (debug-vertex-array.js:31)
    at Model._logDrawCallEnd (base-model.js:447)
    at Model.drawGeometry (base-model.js:213)
    at Model.draw (model.js:122)
```

**Comment by ibgreen** [comment]
Also saw an issue where simply turning on the logs crashed the program (my attributes were `null` for some reason nothing was rendering, and turning on the logs causes the logging to crash as the logger tried to dereference `attribute.value` (unfortunately before printing anything).

**Comment by 1chandu** [comment]
Related :
we should print this log information always : https://github.com/uber/luma.gl/blob/53026ec42d8e6b39feece757c85fd7e9bc1befd8/modules/webgl/src/context/context.js#L195

Change `log.once(1, ...  => log.once(0, ...`

**Comment by ibgreen** [comment]
I think it is OK to only print it when `priority` is `> 0`. Some people get annoyed by us printing to their console, and it is easy enough for us to set `priority` and reload.

Except... Since we use `log.once` nothing is printed on the reload. So as an alternative, just change that to a `log.info` and we are good?

**Comment by 1chandu** [comment]
> Except... Since we use log.once nothing is printed on the reload. So as an alternative, just change that to a log.info and we are good?

Yeah, that should be good.

**Comment by ibgreen** [comment]
WebGL1 is not supported in v9
