### ISSUE TITLE
Should assembleShader declare #version 100 es when version unspecified?

### ISSUE THREAD

**Issue by trxcllnt** [visgl/luma.gl#1205]
I noticed `assembleShader` doesn't declare a GLSL version when one isn't specified:
https://github.com/uber/luma.gl/blob/9c56079a055fd4821096f7671ad66005bb076d3f/modules/shadertools/src/lib/assemble-shaders.js#L75-L84

Should it default to `#version 100 es` like in OpenGL ES 2.0, or does this cause issues in WebGL 1.0? 

@raub and I are working on some [native addons](https://github.com/trxcllnt/node-3d) to provide an OpenGL-backed WebGL context in node, so browser-based WebGL apps can run unmodified in GLFW and render via OpenGL.

Linux and Windows' GL 4.6 are working fine as-is, but MacOS's GL 4.1 is strictly enforces the shader version definition, so the luma.gl lesson examples are choking on shader compilation.

**Comment by ibgreen** [comment]
assembleShaders has the ability to transpile GLSL between versions so it makes sense that it is rigorous with specifying which version it emits. I would land this and just keep an eye out during testing to see we run into problems on some platform.

**Comment by tsherif** [comment]
This is a great idea. Generally, breaking away from the "none or 300" restriction on setting the version would prepare us for newer standards that are on the way (e.g. 310 es for WebGL compute, any GLSL for spir-v implementations of WebGPU).

**Comment by ibgreen** [comment]
GLSL 1.00 is no longer supported in v9
