### ISSUE TITLE
Fix float color attachment texture support check

### ISSUE THREAD

**Issue by 1chandu** [visgl/luma.gl#1256]
Rendering to 32 bit float textures in WebGL1 is supported through [WEGL_color_buffer_float](https://www.khronos.org/registry/webgl/extensions/WEBGL_color_buffer_float/), but at the same time, as per [OES_texture_float](https://www.khronos.org/registry/webgl/extensions/OES_texture_float/) extension, it is implicitly supported **depending** upon the implementation.

Based on the experiments following checks are needed to verify support for this feature :
- Chrome and Firefox : These are WebGL2 browsers, just checking for `EXT_color_buffer_float` suffice.
- Safari (Mac OS) : WebGL1 browsers, implicitly supported when `OES_texture_float` is supported.
- Safari (iOS): WebGL1 browser, not supported even though `OES_texture_float` is supported.

So the best way to verify support for this feature is, create a Framebuffer with float color attachment and check for Framebuffer completeness.

**Comment by ibgreen** [comment]
WebGL1 support has been dropped in v9
