### ISSUE TITLE
Error message for linking error is not informative

### ISSUE THREAD

**Issue by unconed** [visgl/luma.gl#1395]
#### Actual Result
Error message for shader linking errors is not informative:
`program not linked`

#### Expected Result
Error message describes specific problem, e.g.:
`ERROR: Implementation limit of 16 MAX_VERTEX_ATTRIBS (e.g., number of generic plus conventional active vec4 attributes) exceeded, shader uses up to vec4 attribute 19.`

#### Reproduce Steps
Put too many attributes inside a vertex shader.

#### To Do List 
  - [ ] Add label and assign to milestone
  - [x] Coding
  - [ ] Test

**Comment by ibgreen** [comment]
We'll publish a new patch release for 8.2 soon with this commit included.

BTW, I love your work on mathbox and shadergraph, very inspirational!

I have been playing with the idea of trying to integrate them with luma.gl and deck.gl on more than one occasion :)
