### ISSUE TITLE
Remove gltools side effect

### ISSUE THREAD

**Issue by Pessimistress** [visgl/luma.gl#1404]
See https://github.com/visgl/deck.gl/issues/4969

The following orphan code may be optimized away:

https://github.com/visgl/luma.gl/blob/9384106f180a413b4652a0bd2df3d13ca451a0de/modules/gltools/src/polyfill/polyfill-context.js#L32-L33

Users of the polyfill function should import it directly from the module, instead of relying on a global variable.

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by ibgreen** [comment]
Fixed in v9
