### ISSUE TITLE
Renderbuffer.getSamplesForFormat cause error maximum call stack size exceeded

### ISSUE THREAD

**Issue by littleTigerRunRunRun** [visgl/luma.gl#1413]
A bug that when you use the Renderbuffer.getSamplesForFormat, the code will get a error "Maximum call stack size exceeded"
will happen in code like this: 

### code start
import { Renderbuffer } from '@luma.gl/webgl'
import GL from '@luma.gl/constants'

// I get gl from the AnimationLoop
Renderbuffer.getSamplesForFormat(gl, { format: GL.RGBA8 })
### code end

I'm sure my chrome get the webgl2 render context.

#### Actual Result
get an error
#### Expected Result
get the samples i can use back

**Comment by ibgreen** [comment]
No Renderbuffers in v9
