### ISSUE TITLE
Only in Chrome Android: GLSL compilation errors in vertex shader 

### ISSUE THREAD

**Issue by bttb** [visgl/luma.gl#1457]
I use DeckGL (8.4.5) and DeckGL uses Luma (8.4.4).

I want to display circles on a Google Map. This worked until I updated luma from 8.4.2 to 8.4.4 a few days ago. DeckGl was and is 8.4.5. Now I get this error ONLY in Chrome on Android:

luma.gl: GLSL compilation errors in vertex shader scatterplot-layer-vertex-shader-1

All other browser I tested are working (including Opera and Mozilla on Android, Chrome on iOS and Chrome on Windows).

luma.log.priority=2 does not change the output I get.

I have no idea how to catch this error to offer an alternative approach without WebGL. Or what to do to not get this error.

**Comment by Pessimistress** [comment]
There is a bug in Chrome 89 for Android, see https://github.com/visgl/deck.gl/issues/5557
