### ISSUE TITLE
brdfLUT.png from pbr test has been moved

### ISSUE THREAD

**Issue by JannikGM** [visgl/luma.gl#1471]
This URL is no longer valid:

https://github.com/visgl/luma.gl/blob/e0df967b7442c98263f5888bf711bc4e5f629191/test/apps/pbr/mesh.js#L432

A working link (in an older tagged revision) is: https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Viewer/glTF-WebGL-PBR-final/textures/brdfLUT.png

**Comment by ibgreen** [comment]
@belom88 @atomicra perhaps your team could take a look at this issue?
