### ISSUE TITLE
question: how to convert old loadTextures method to new format

### ISSUE THREAD

**Issue by tamir-jether** [visgl/luma.gl#1488]
Im trying to use an old luma.gl example. So im trying to convert old methods to newer versions methods.

Reading the docs, i know `loadTextures` is deprecated and i should now use:
`new Texture(gl, {data: url, parameters})`

But lets say i have something like that:

      loadTextures(gl, {
      urls: [url],
      parameters: {
        parameters: {
          [GL.TEXTURE_MAG_FILTER]: GL.LINEAR,
          [GL.TEXTURE_MIN_FILTER]: GL.LINEAR,
          [GL.TEXTURE_WRAP_S]: GL.CLAMP_TO_EDGE,
          [GL.TEXTURE_WRAP_T]: GL.CLAMP_TO_EDGE
        }
      }
       }).then(textures => {
          this.setState({texture: textures[0]});
        });

How should i convert this snippet to use the new format?

**Comment by ibgreen** [comment]
Without looking closely at the API and making sure this exact code is working before posting, it would be something like:
```typescript
 this.setState({texture: new Texture2D(gl, {
    parameters: {
      [GL.TEXTURE_MAG_FILTER]: GL.LINEAR,
      [GL.TEXTURE_MIN_FILTER]: GL.LINEAR,
      [GL.TEXTURE_WRAP_S]: GL.CLAMP_TO_EDGE,
      [GL.TEXTURE_WRAP_T]: GL.CLAMP_TO_EDGE
    }
  });
```
