### ISSUE TITLE
Circular dependency in @luma.gl/webgl

### ISSUE THREAD

**Issue by Pessimistress** [visgl/luma.gl#1493]
Originally reported in https://github.com/visgl/deck.gl/issues/6134

Rollup is failing to resolve dependencies correctly because of circular references.

`Resource`, `Buffer`, `Texture`, `Framebuffer` etc. import utilities from `/webgl-utils`:
https://github.com/visgl/luma.gl/blob/d766813a6ec34b12137c1dc870c24b21724a3739/modules/webgl/src/classes/resource.js#L3

`/webgl-utils` imports `/webgl-utils/texture-utils`:
https://github.com/visgl/luma.gl/blob/d766813a6ec34b12137c1dc870c24b21724a3739/modules/webgl/src/webgl-utils/index.js#L12

`/webgl-utils/texture-utils` imports `Texture`, `Framebuffer`:
https://github.com/visgl/luma.gl/blob/d766813a6ec34b12137c1dc870c24b21724a3739/modules/webgl/src/webgl-utils/texture-utils.js#L2-L5

The classes do not really depend on texture-utils, and we should avoid referencing them.

Proposed fix is to remove `/utils/index.js` and `/webgl-utils/index.js`, and import all utilities directly from the files that they are defined in.

The fix should be tested against this repo: https://github.com/clarknova/deck.gl-vite-minimal-example

**Comment by ibgreen** [comment]
@belom88 @morphoix - any chance you can make a PR on this?

**Comment by morphoix** [comment]
> @belom88 @morphoix - any chance you can make a PR on this?

I can take a look after PR for Shan 
my prediction - the day after tomorrow or smth around :)

**Comment by ibgreen** [comment]
Investigations are indicating that this is fixed indepedently on master. See comments in PR: https://github.com/visgl/luma.gl/pull/1499#issuecomment-991794164
