### ISSUE TITLE
Circular dependency - copy-and-blit.js

### ISSUE THREAD

**Issue by Arthurgoujon** [visgl/luma.gl#1549]
The following circular dependency: 
Error: Circular dependency: node_modules\@luma.gl\webgl\dist\es5\classes\framebuffer.js -> node_modules\@luma.gl\webgl\dist\es5\classes\copy-and-blit.js -> node_modules\@luma.gl\webgl\dist\es5\classes\framebuffer.js

Is causing a runtime error when bundling my code with Rollup and when using one of the following libraries: 
- https://deck.gl/docs/api-reference/layers/icon-layer 
- https://deck.gl/docs/api-reference/layers/geojson-layer

For now the manual fix was to copy function copyToDataUrl to framebuffer.js to avoid importing it from copy-and-blit.js. 

Should this circular dependency be addressed or is Rollup the problem here?

**Comment by Pessimistress** [comment]
I agree that we should generally avoid circular dependencies.

However I'm trying to understand how this did not come up before - did Rollup recently updated?

**Comment by Arthurgoujon** [comment]
I have no idea really, I never used Rollup before but I have to for this particular project. 
Just for information below are a bunch of other circular dependencies highlighted by rollup when building. What I don't understand is why I get don't get any of this with webpack: no warnings, no errors at runtime. It makes me think that the solution might actually be rather in the rollup config somewhere.

Error: Circular dependency: node_modules\@luma.gl\gltools\dist\es5\state-tracker\unified-parameter-api.js -> node_modules\@luma.gl\gltools\dist\es5\state-tracker\track-context-state.js -> node_modules\@luma.gl\gltools\dist\es5\state-tracker\unified-parameter-api.js
Error: Circular dependency: node_modules\@luma.gl\gltools\dist\es5\state-tracker\unified-parameter-api.js -> node_modules\@luma.gl\gltools\dist\es5\state-tracker\track-context-state.js -> C:\Users\arthurgoujon\Documents\Mendix\deckglwidget-main\customWidgets\davidtest\node_modules\@luma.gl\gltools\dist\es5\state-tracker\unified-parameter-api.js?commonjs-proxy -> node_modules\@luma.gl\gltools\dist\es5\state-tracker\unified-parameter-api.js
Error: Circular dependency: node_modules\@luma.gl\webgl\dist\es5\classes\framebuffer.js -> node_modules\@luma.gl\webgl\dist\es5\features\index.js -> node_modules\@luma.gl\webgl\dist\es5\features\webgl-features-table.js -> node_modules\@luma.gl\webgl\dist\es5\classes\framebuffer.js
Error: Circular dependency: node_modules\@luma.gl\webgl\dist\es5\classes\framebuffer.js -> node_modules\@luma.gl\webgl\dist\es5\features\index.js -> node_modules\@luma.gl\webgl\dist\es5\features\webgl-features-table.js -> C:\Users\arthurgoujon\Documents\Mendix\deckglwidget-main\customWidgets\davidtest\node_modules\@luma.gl\webgl\dist\es5\classes\framebuffer.js?commonjs-proxy -> node_modules\@luma.gl\webgl\dist\es5\classes\framebuffer.js
Error: Circular dependency: node_modules\@math.gl\web-mercator\dist\es5\web-mercator-viewport.js -> node_modules\@math.gl\web-mercator\dist\es5\fit-bounds.js -> node_modules\@math.gl\web-mercator\dist\es5\web-mercator-viewport.js
Error: Circular dependency: node_modules\@math.gl\web-mercator\dist\es5\web-mercator-viewport.js -> node_modules\@math.gl\web-mercator\dist\es5\fit-bounds.js -> C:\Users\arthurgoujon\Documents\Mendix\deckglwidget-main\customWidgets\davidtest\node_modules\@math.gl\web-mercator\dist\es5\web-mercator-viewport.js?commonjs-proxy -> node_modules\@math.gl\web-mercator\dist\es5\web-mercator-viewport.js

**Comment by donmccurdy** [comment]
This is addressed in v9 (upcoming), where `webgl-framebuffer.ts` no longer depends on `copy-and-blit.ts`.
