### ISSUE TITLE
GLSL100 transpiling fails to convert 'in highp float myVariable'

### ISSUE THREAD

**Issue by MGraefe** [visgl/luma.gl#1602]
Using luma.gl 8.5.10, transpiling of the following line of shader code to GLSL100 leaves the following line unchanged:
```
in highp float myVariable;
```
This then produces a compilation error: 
> ERROR: 'in' : storage qualifier supported in GLSL ES 3.00 and above only

Instead, this line should be transpiled to:
```
attribute highp float myVariable;
```

I believe it did so for older luma.gl versions, at least our problems only popped up after updating deck (and thus luma).
Probably not really an urgent bug, especially because slapping on 'precision highp float' and calling it a day works just fine on modern platforms and it would probably even work without any precision specifier at all. Just wanted to document this.

**Comment by ilan-gold** [comment]
I saw this as well: #1624
