### ISSUE TITLE
Chrome 98 Compilation Issue

### ISSUE THREAD

**Issue by ilan-gold** [visgl/luma.gl#1624]
See https://portal.hubmapconsortium.org/browse/dataset/cd880c54e0095bad5200397588eccf81 on Chrome 98 (look at browser console).  I don't think this was happening previously - one should be able to copy the full text of the shader from the log.
#### Actual Result
The shaders that rely on WebGL2 capabilities (`usamplerXX` and `xsampler3D`) seem to have broken.

#### Expected Result
The shaders should compile as before.

#### Reproduce Steps
This is the best I have for now.  Will keep digging.  Figured I'd share.

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
Here's the error I see:

```
^^^ ERROR: 'usampler2D' : No precision specified
```

Do you have the full shader code?

**Comment by ilan-gold** [comment]
@Pessimistress I forgot I posted this - just upgrading deck.gl/viv seemed to fix the issue even though I hadn't actually changed anything.  Not sure what is up with this but if I notice it again, I will re-open.
