### ISSUE TITLE
Memory Usage weird Stats 

### ISSUE THREAD

**Issue by dryabinin-actionengine** [visgl/luma.gl#1630]
I am using luma stats and probe.gl stats widget to display statistics of memory usage in react application.
There are differences between using luma statistics in **dev** and **production** mode. In production mode I get some `fv Memory` and `iv Memory` stats. My guess this issue occurs because of code minification process.

Dev Mode:
![image](https://user-images.githubusercontent.com/70207219/157402553-743084e1-8162-4f8c-b4b8-e80a799d9030.png)
Production Mode:
![image](https://user-images.githubusercontent.com/70207219/157402659-dd21d0f3-904f-4086-aa36-45403b08e8b6.png)

#### Actual Result
![image](https://user-images.githubusercontent.com/70207219/157402659-dd21d0f3-904f-4086-aa36-45403b08e8b6.png)
#### Expected Result
![image](https://user-images.githubusercontent.com/70207219/157402553-743084e1-8162-4f8c-b4b8-e80a799d9030.png)
#### Reproduce Steps

1. Go to https://github.com/visgl/loaders.gl-showcases
2. Clone repo
3. cd loaders.gl-showcases
4. yarn
5. yarn start
6. Go to `http://localhost:3000/viewer`
7. See that statistics don't have any `fv Memory`  or `iv Memory` stats
8. Change mode to "production" in webpack.dev.config.js file.
9. yarn start
10. Go to `http://localhost:3000/viewer`
11. . See that statistics have `fv Memory`  or `iv Memory` stats

**Comment by ibgreen** [comment]
On 8.5-release branch this is likely the culprit: https://github.com/visgl/luma.gl/blob/8.5-release/modules/webgl/src/classes/resource.js#L287 as `constructor.name` does indeed get minified.

On master (9.0-alpha) this code has change to use `Symbol.toStringTag` which should not suffer from this problem.

However the changes on master are very big (WebGPU refactor!), so I recommend making a separate fix on 8.5-release.
