### ISSUE TITLE
GLTFInstantiator mutates input data

### ISSUE THREAD

**Issue by Pessimistress** [visgl/luma.gl#1762]
#### Actual Result

`GLTFInstantiator.instantiate` adds `_node` and `_mesh` fields to node and mesh:

https://github.com/visgl/luma.gl/blob/c2f05340f3cdd49d02a37f097378cb7132cf196d/modules/experimental/src/gltf/gltf-instantiator.js#L60

https://github.com/visgl/luma.gl/blob/c2f05340f3cdd49d02a37f097378cb7132cf196d/modules/experimental/src/gltf/gltf-instantiator.js#L99-L100

This prevents the gltf object from being used to create another instance, and there is no easy way to undo this change.

#### Expected Result

Input object should not be mutated.

#### Reproduce Steps
https://github.com/visgl/deck.gl/issues/7950

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by ibgreen** [comment]
I suppose a quick fix for 8.5 would be to deep clone everything (except arraybuffers) before instantiating.

That is probabely appropriate since for 9.0 the gltf instantiation needs to be refactored quite extensively.
