### ISSUE TITLE
picking shader error "global variable initializers must be constant expressions"

### ISSUE THREAD

**Issue by Seungup** [visgl/luma.gl#1801]
After updating from `9.0.0-alpha.30` to `9.0.0-alpha.34`, the picking module fails.

Verify that the addDefaultModule method in `PipelineFactory` has been removed
I changed it to use it after I registered for the `ShaderAssembler` class.

```typescript
import { PipelineFactory } from '@luma.gl/engine';

const pipelineFactory = PipelineFactory.getDefaultPipelineFactory(device);
pipelineFactory.addDefaultModule( ... );
```

```typescript
import { ShaderAssembler } from '@luma.gl/shadertools';

const shaderAssembler = ShaderAssembler.getDefaultShaderAssembler();
shaderAssembler.addDefaultModule( ... );
```

The following error occurs in the `picking` shader moudle.

![image](https://github.com/visgl/luma.gl/assets/53374248/63b336a3-69b1-416d-94df-4748f0172fbc)

```glsl
// picking moudle

float COLOR_SCALE = 1. / picking_uColorRange; 
                  ^ Initialization failed on here.
```
An error occurs that fails to initialize the following `COLOR_SCALE` values.

Verified that it works normally when changing to the `#define` syntax.

```typescript
import { picking } from '@luma.gl/shadertools';

picking.vs = picking.vs.replace(
  'float COLOR_SCALE = 1. / picking_uColorRange;',
  '#define COLOR_SCALE (1. / picking_uColorRange)'
);
```

```glsl
#define COLOR_SCALE (1. / picking_uColorRange)
```

**Comment by ibgreen** [comment]
@Seungup thanks for reporting. Should be fixed in alpha.35.
