### ISSUE TITLE
error in webgpu compute example

### ISSUE THREAD

**Issue by gouldingken** [visgl/luma.gl#1844]
I understand this is in alpha and it's still under development, but I thought it best to report this error that crops up if I try to run the example in 
https://github.com/visgl/luma.gl/blob/master/examples/webgpu/compute/app.ts
```
Uncaught (in promise) TypeError: Cannot set property info of #<_WebGPUDevice> which has only a getter
    at new Device (device.ts:231:12)
    at new _WebGPUDevice (webgpu-device.ts:100:5)
    at _WebGPUDevice.create (webgpu-device.ts:92:20)
```

**Comment by ibgreen** [comment]
Moved into wip folder to avoid confusion.
