### ISSUE TITLE
Picking not working with uniform block

### ISSUE THREAD

**Issue by felixpalmer** [visgl/luma.gl#1850]
#### Actual Result

When adding this `picking` module to a `Model` an error is raised:

```
Uncaught Error: No value for binding pickingUniforms in unnamed
    at WEBGLRenderPipeline._applyBindings (webgl-render-pipeline.ts:405:15)
    at WEBGLRenderPipeline.draw (webgl-render-pipeline.ts:242:10)
    at _Model.draw (model.ts:240:19)
    ...
```

#### Expected Result

Picking module can be added without issue

#### Reproduce Steps

Modify `examples/tutorials/hello-cube/app.ts` so that `this.model` contains `modules: [picking]` (`import {picking} from '@luma.gl/shadertools';`)

**Comment by ibgreen** [comment]
picking module is used in the instancing example with some explicit handling. 

I expect that you are looking for luma to automatically initialize and bind the uniform buffer?

**Comment by felixpalmer** [comment]
Yes that would be nice. I will try and follow the instancing example to get it working in deck

**Comment by ibgreen** [comment]
I think the ShaderInputs system takes care of this now, if not please reopen.
