### ISSUE TITLE
@luma.gl/webgl clear func causing an error

### ISSUE THREAD

**Issue by sakitam-fdd** [visgl/luma.gl#1903]
The status related to stencil seems to be set to the depth state, and I am not sure if this is intentional or a bug

https://github.com/visgl/luma.gl/blob/master/modules/webgl/src/classic/clear.ts#L53-L58

![image](https://github.com/visgl/luma.gl/assets/19517451/7d31d43c-cd43-48ec-9fb4-b4f2147f182d)

![image](https://github.com/visgl/luma.gl/assets/19517451/ce719763-ba16-452e-989c-f5c92014eab3)

**Comment by ibgreen** [comment]
It looks like you are debugging your app with spector js and spector tries to read some data from luma.gl and does not see what it expected?

Not sure how to help you debug this.

**Comment by sakitam-fdd** [comment]
@ibgreen 
It occurs when clear is called, as shown in the following code
```js
import { Framebuffer, Renderbuffer, Texture2D, clear } from '@luma.gl/webgl';

// other render pass
clear(this.gl, {
  color: true,
  stencil: true,
  // depth: false,
});
```

The error was raised when the depth parameter was not specified, and I noticed that when stencil was specified without depth, clearStencil had a value of null

```js
if (stencil) {
  clearFlags |= GL_STENCIL_BUFFER_BIT;
  if (depth !== true) {
    parameters.clearStencil = depth;
  }
}
```
