### ISSUE TITLE
@luma.gl/shadertools regular expression for getShaderName unable to resolve the correct shader name

### ISSUE THREAD

**Issue by sakitam-fdd** [visgl/luma.gl#1923]
getShaderName in shadertools will not return the correct result，This is caused by incorrect regular expressions

https://github.com/visgl/luma.gl/blob/HEAD/modules/shadertools/src/lib/glsl-utils/get-shader-info.ts#L20-L25

This was first reported by  @Randysheng 

#### Actual Result

https://jex.im/regulex/#!flags=&re=%23define%5B%5Cs*%5DSHADER_NAME%5B%5Cs*%5D(%5BA-Za-z0-9_-%5D%2B)%5B%5Cs*%5D

#### Expected Result

https://jex.im/regulex/#!flags=&re=%23define%5Cs*SHADER_NAME%5Cs*(%5BA-Za-z0-9_-%5D%2B)%5Cs*

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by ibgreen** [comment]
Thanks for reporting! Are you willing to create a quick PR? We should probably add a test case or two as well.
