### ISSUE TITLE
Consider using texStorage2D in Texture2D class for WebGL2

### ISSUE THREAD

**Issue by howtimeflies0** [visgl/luma.gl#193]
This method creates immutable textures that have better performance.

according to https://www.khronos.org/registry/webgl/specs/latest/2.0/

> void texStorage2D(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height) (OpenGL ES 3.0.4 §3.8.4, man page)
Specify all the levels of a two-dimensional or cube-map texture at the same time. 

> The image contents are set as if a buffer of sufficient size initialized to 0 would be passed to each texImage2D call in the pseudocode in The OpenGL ES 3.0 specification section 3.8.4 (OpenGL ES 3.0.4 §3.8.4).

> texStorage2D should be considered a preferred alternative to texImage2D. It may have lower memory costs than texImage2D in some implementations.

**Comment by ibgreen** [comment]
Finally implemented on master

**Comment by ibgreen** [comment]
Implemented in v9.1
