### ISSUE TITLE
`Model` does not respect `'line-strip'` `topology` in `geometry` prop

### ISSUE THREAD

**Issue by felixpalmer** [visgl/luma.gl#1984]
#### Actual Result

`Model` does not respect `'line-strip'` `topology` if `Geometry` passed as prop, but works when forced with `setGeometry`:

https://github.com/visgl/deck.gl/pull/8567/commits/3767ffd5bc291ce654cdf4b5cb0d370fe98a2219

#### Expected Result

`geometry` prop works without needing to use `setGeometry`

#### Reproduce Steps

Revert above commit in deck and run render tests, `geojson-extruded-lnglat` will now fail

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
The problem is that with #1953, WebGL pipeline is reused for different topologies, but topology is not passed as an option into `pipeline.draw`:

https://github.com/visgl/luma.gl/blob/9fefd26f24c882dfb221812cece8febb74389a52/modules/webgl/src/adapter/resources/webgl-render-pipeline.ts#L196
