### ISSUE TITLE
Missing changelog / release tags v9.0

### ISSUE THREAD

**Issue by birkskyum** [visgl/luma.gl#2026]
The [changelog](https://github.com/visgl/luma.gl/blob/master/CHANGELOG.md), and the [releases](https://github.com/visgl/luma.gl/releases) are lagging behind the [public versions](https://www.npmjs.com/package/@luma.gl/core).

**Comment by ibgreen** [comment]
Hmm, yes 
- we don't have git releases integration in luma.gl. 
- And the package was published from the 9.0-release branch: https://github.com/visgl/luma.gl/blob/9.0-release/CHANGELOG.md

We usually rely on the website "what's new" page but the luma.gl site went down when we republished for 9.0. Looks like the usual circus of github immediately releasing the lock on our domain if we make a minuscule error when publishing our github pages, sigh. Linux Foundation IT is working on it.
