### ISSUE TITLE
ShaderLayout incorrectly infered if there was a previous Model

### ISSUE THREAD

**Issue by felixpalmer** [visgl/luma.gl#2036]
#### Actual Result

`getShaderLayout()` is not stateless, returning incorrect (non-existant) uniform sampler bindings, if it has been invoked on another `Model` before.

#### Expected Result

Introspection works independently of any previously created `Model`s

#### Reproduce Steps

Scenario A: Run https://felixpalmer.github.io/deck.gl/examples/scatterplot-layer - it will work fine

Scenario B: Run https://felixpalmer.github.io/deck.gl/examples/google-3d-tiles and *then* https://felixpalmer.github.io/deck.gl/examples/scatterplot-layer and observe error:

```
No value for binding terrain_map in scatter-plot-cached
```

If a breakpoint is set in `webgl-render-pipeline.ts` at the point where the layout is introspected, we see the difference:

Scenario A: 
<img width="853" alt="Screenshot 2024-03-14 at 15 45 10" src="https://github.com/visgl/luma.gl/assets/453755/0a6d7446-7555-4907-8949-5035528946cc">

Scenario B: 
<img width="832" alt="Screenshot 2024-03-14 at 15 45 37" src="https://github.com/visgl/luma.gl/assets/453755/fafe9514-48ee-4b3d-bac0-df0be3379bd7">

Digging deeper, setting a breakpoint at the point at which we call [gl.getProgramParameter(program, GL.ACTIVE_UNIFORMS)](https://github.com/visgl/luma.gl/blob/master/modules/webgl/src/adapter/helpers/get-shader-layout.ts#L163) we see the GPU has a different number of uniforms bound in each scenario.

Perhaps we are not cleaning up the bound samplers somewhere?

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by ibgreen** [comment]
Hmm, this looks weird.

One thought is one can get weird data back from these introspection methods if program linking fails.

I can't apot anything untoward, but it may be worth putting a breakpoint or log in `WEBGLRenderPipeline._getLinkStatus()` just in case.

**Comment by felixpalmer** [comment]
Update:

In the `WebGLRenderPipeline` constructor, in Scenario B we have:

```js
props.shaderAssembler._defaultModules.map(m => m.name).includes('terrain')
```

returning `true`, so somehow the `terrain` module is getting stuck in the `defaultModules`. In other words, this is not an issue with the introspection
