### ISSUE TITLE
`convertBlendFactorToFunction()` doesn't support all constants from `BlendFactor`

### ISSUE THREAD

**Issue by felixpalmer** [visgl/luma.gl#2039]
#### Reproduce Steps

`convertBlendFactorToFunction('blendColorSrcFactor', 'blend-color')` is not going to work as the [mapping](https://github.com/visgl/luma.gl/blob/master/modules/webgl/src/adapter/converters/device-parameters.ts#L379-L390) doesn't include the following keys [present](https://github.com/visgl/luma.gl/blob/master/modules/core/src/adapter/types/parameters.ts#L132-L134) in `BlendFactor`:

- `'src-alpha-saturated'`
- `'blend-color'`
- `'one-minus-blend-color'`

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by donmccurdy** [comment]
PR:

- https://github.com/visgl/luma.gl/pull/2040
