### ISSUE TITLE
Spector.js errors with error `glState.push is not a function`

### ISSUE THREAD

**Issue by tjni** [visgl/luma.gl#2080]
I was going through the [debugging section](https://luma.gl/docs/developer-guide/debugging/) of the docs and wanted to try out Spector.js, but ran into console errors.

#### Actual Result

<img width="1727" alt="Screenshot 2024-04-26 at 9 24 11 AM" src="https://github.com/visgl/luma.gl/assets/3806110/2e8ec878-7914-47d5-96e8-bf95e767d2e3">

#### Expected Result

That this error doesn't occur.

#### Reproduce Steps

1. Install the Spector.js extension.
2. Load this example: https://github.com/visgl/deck.gl/tree/master/examples/website/arc
3. Run `luma.log.set('spector', true);` in the console and reload.
4. Give the extension access to the page (if on localhost, for example).

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by ibgreen** [comment]
Thanks for reporting . Somehow spectorJS seems to be able to get a fresh, non-instrumented context from the canvas related to the device's WebGL context (perhaps webgl1 vs webgl2). Proposed fix is to initialize spectorJS with context not canvas.

**Comment by ibgreen** [comment]
Issue is fixed on master (9.1-alpha).  A fix could be done on 9.0, the main issues are:
- the spector CDN is currently down, use jsdeliver instead, 
- spectorjs needs to be installed before luma.gl's instrumentation as spector now seems to clobber luma's instrumentation state.
