### ISSUE TITLE
Add `depthTest` to `Parameters`

### ISSUE THREAD

**Issue by Napam** [visgl/luma.gl#2096]
The `Parameteres` type is missing `depthTest`. This makes it inconvenient when you want to use it, or create custom layers in `deck.gl`, as Typescript cannot infer that it is a thing, thus an enhancement is to add it to to the `Parameters`, which in turn is defined like this:

```typescript
export type Parameters = _RenderParameters &
  DepthStencilParameters &
  ColorParameters &
  MultisampleParameters;
```

I have tried locally to add it _RenderParameters and everything built fine. Not sure if _RenderParameters is the right place to do it though, or maybei t is `DepthStencilParameters`

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update: `depthTest` is now added to to the `Parameters` type
  - [ ] Test: Built fine

**Comment by ibgreen** [comment]
The parameter in v9 is aligned with WebGPU and is called `depthCompare` https://luma.gl/docs/api-reference/core/parameters
