### ISSUE TITLE
[9.1] ShaderInputs does not resolve uniforms from shader module dependencies

### ISSUE THREAD

**Issue by Pessimistress** [visgl/luma.gl#2118]
9.0 contains https://github.com/visgl/luma.gl/commit/6785d60015d9dd30b2dddc691738eb1f645545c9
While master reverted the change https://github.com/visgl/luma.gl/pull/2078

#### Reproduce Steps

https://github.com/visgl/luma.gl/commit/2f1da4a69f50bea6670d5427aa58cc7394e5c998

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by ibgreen** [comment]
> 9.0 contains [6785d60](https://github.com/visgl/luma.gl/commit/6785d60015d9dd30b2dddc691738eb1f645545c9) While master reverted the change #2078

Not really. It was landed by mistake by me and immediately reverted as it wasn't ready to land. 

As discussed in https://github.com/visgl/luma.gl/pull/2073#discussion_r1570764819 I was making a big refactor on master to remove the need for some unwanted complexity in this PR. 

Those changes are landed now so this PR needs to be reopened /rebased based on the new master.

@felixpalmer are you still up for it?
