### ISSUE TITLE
`rbg8norm-webgl` Texture Format missing

### ISSUE THREAD

**Issue by ilan-gold** [visgl/luma.gl#2124]
#### Actual Result
If I try to use `rbg8norm-webgl` I get:

`deck: initialization of BitmapLayerWrapper({id: 'tile-sub-layer-0,16384,16384,0-Tiled-Image-TiffPixelSource-#detail#-0-0--5-wrapped'}): Unsupported texture format rbg8norm-webgl Error: Unsupported texture format rbg8unorm-webgl`

which is expected I guess since it is not supported: https://luma.gl/docs/api-reference/core/texture-formats/#formats
#### Expected Result

I would expect this to work but I don't know enough as to why it does not.  Maybe some perspective here would be nice. We rely on three-channel rendering because brightfield microscopy data is saved often with only three channels (see e.g., https://github.com/hms-dbmi/viv/blob/fb2f7f00f2ad670ecbe4b000ec5ac75dc5fe82ee/packages/layers/src/multiscale-image-layer/multiscale-image-layer.js#L111-L112)

I'd rather not add another channel because this will eat up CPU time.

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by ilan-gold** [comment]
As some context, we are upgrading Viv: https://github.com/hms-dbmi/viv/pull/805

If you need a nice testing ground for some features, I can point you to images for different dtypes (`float32`, `float16` `int8` etc.) and also 2D vs. 3D.

I noticed https://github.com/visgl/luma.gl/issues/2115 and @xinaesthete  found https://github.com/visgl/luma.gl/pull/2123 which seems to state that a number of texture types are broken.  We are happy to do some battle testing because we will update to point an `main` anyway.

**Comment by donmccurdy** [comment]
Context:

- https://github.com/gpuweb/gpuweb/issues/66

Many devices do not support rgb8. In WebGL, this means your texture data is implicitly converted from rgb8 to rgba8 on these devices, which (as you mention) is not very efficient. In WebGPU, rgb8 is simply disallowed.

LumaGL is moving toward first-class WebGPU support, so my feeling is that we probably do not want to hide an expensive conversion to rgba8 from the application. Similarly, three.js and babylon.js have dropped support for rgb8, requiring an explicit conversion by the user.

**Comment by xinaesthete** [comment]
Thanks @donmccurdy I'd just been looking into this and reached a similar conclusion.

**Comment by ibgreen** [comment]
Try luma@9.0.25 https://github.com/visgl/luma.gl/pull/2198
