### ISSUE TITLE
Regression in 9.0.25 when using `EditableGeoJsonLayer`

### ISSUE THREAD

**Issue by xinaesthete** [visgl/luma.gl#2222]
I have a repository https://github.com/xinaesthete/deck-editable-test where I'm prototyping some features based on this community layer, but I've noticed that while it works with 9.0.24, installing 9.0.25 leads to errors with shaders not being compiled.

May be to do with aggregation-layers / `'mask'` behaviour etc - haven't dug in detail. Indeed, I was in the process of investigating more of how these features work by trying to activate `spector` debugging etc which lead to some other issues - I've left a few comments in the code / README, really need to get away from my computer & do other things with my weekend now but thought it'd be good to at least raise this as an issue.

**Comment by ibgreen** [comment]
@xinaesthete Thanks for the detailed report, highly appreciated!

> @luma.gl/*@9.0.25 for some reason leads to shader linking errors; downgrading to @luma.gl/*@9.0.24 fixes this.

Looking at https://github.com/visgl/luma.gl/releases/tag/v9.0.25 I can't really see what could have happened. There are 3 small PRs, you can check them yourself. One is a yarn upgrade, one relaxes a restriction on attribute types, and the other fixes the device initialization issue you reported below.

> The typing of the getCursor() method potentially returning null caused a niggle with TS that I currently work-around by sub-classing EditableGeoJsonLayer and overriding that method.
> TransformMode breaks due to behaviour inherited from RotateMode when selectedFeatureIndexes is empty [] - tries to getGuides(), ends up with NaN / Infinity and fails to catch that.

> .. I anticipate using this layer fairly heavily in the near future, so may take on more of the maintenance of it.

Yes we desperately need at least a temporary maintainer for the editable-layers module. If you can make a pass on it I know it would be highly appreciated by many in the community. I don't think it is a heavy commitment, it just needs a little TLC after ~5 years of neglect. You'd have our full support.  I've sent you invites to the luma.gl and deck.gl-community repos

> As soon as any deviceProps are passed to <DeckGL> (even empty {}), we get errors "deck: Cannot access 'WebGPUDevice' before initialization undefined".

This should have been fixed by luma 9.0.25 by https://github.com/visgl/luma.gl/pull/2191.

> Some of the luma documentation needs review, e.g.
> https://luma.gl/docs/api-reference/webgpu/ is inconsistent in referring to WebGL / WebGPU

Thanks for reporting. Fixed by #2224

**Comment by xinaesthete** [comment]
Great, I expect I'll start making an initial pass on editable-layers at least locally in the next couple of days (not today, though - bank holiday here in UK), and glad to contribute where I can. Mostly minor wrinkles to iron out and it does seem as you say something of wide use to the community.

**Comment by ibgreen** [comment]
To accelerate PR approval, if possible, please make small focused PRs tackling one thing at a time. We can chat on the open visualization slack as well or in the discussions tab here on github to get agreement before you do too much work.

**Comment by xinaesthete** [comment]
I think the main issue I have here is to do with `'compilation-status-async-webgl'` btw, and probably not specific to the `EditableGeoJsonLayer` but that happened to be what I was focussed on when I noticed the issue & didn't have time to dig.

**Comment by xinaesthete** [comment]
I switched that project to use yarn - gradually trying to figure out how to link to local versions for development, for which I might start a bit more of a discussion on slack or something.

Interestingly, the issue doesn't seem to present with yarn. When I was using npm with 9.0.25, looking at `vertex-format-from-attribute.js` in devtools didn't seem to include the changed lines

```
  // TODO - Special cases for WebGL (not supported on WebGPU), overrides the check below
  if (dataType === 'uint8' && normalized && components === 1) {
    return 'unorm8-webgl';
  }
  if (dataType === 'uint8' && normalized && components === 3) {
    return 'unorm8x3-webgl';
  }
```

I'm still very unclear what exactly is going wrong, but with npm I consistently see errors "vertex shader is not compiled" in 9.0.25 and not in 24. Could it be some kind of issue in the deployment process?

**Comment by ibgreen** [comment]
> Could it be some kind of issue in the deployment process?

It is possible. We have done a lot of work on moving our publish process to CI (github actions) rather than doing less reliable local publishes, though we now have two different branches with different iterations of that system (9.0-release and master).

@felixpalmer since you have been publishing successfully from 9.1 (with the exception of 9.0.25 that was published by me), would you consider publishing a 9.0.26 to see if we can make this issue go away?

**Comment by felixpalmer** [comment]
@xinaesthete can you try with [9.0.26](https://www.npmjs.com/package/@luma.gl/core/v/9.0.26)?

**Comment by xinaesthete** [comment]
> @xinaesthete can you try with [9.0.26](https://www.npmjs.com/package/@luma.gl/core/v/9.0.26)?

Success in updating an npm version working with 9.0.25 to 9.0.26 without anything breaking.

**Comment by xinaesthete** [comment]
Less success in updating the yarn version I'm afraid.

I edited `package.json` manually so that the two luma dependencies changed to `"^9.0.26"`, then ran `volta run yarn install` & `volta run yarn dev`.

I get this:

```
Error: The following dependencies are imported but could not be resolved:

  @deck.gl/extensions (imported by /Users/petertodd/code/www/deck-editable-test/src/App.tsx)

Are they installed?
```

**Comment by xinaesthete** [comment]
Removing `yarn.lock` and re-installing works ok. I'm not very familiar with yarn and there may be more reasons for generally not editing package.json that I wasn't considering.

For ref, warnings from yarn install at the moment.

```
➤ YN0000: · Yarn 4.4.0
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @deck.gl-community/editable-layers@npm:9.0.3, @deck.gl-community/layers@npm:9.0.3, @eslint/js@npm:9.9.1, @luma.gl/engine@npm:9.0.26, and 638 more.
➤ YN0000: └ Completed in 16s 594ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0002: │ deck-editable-test@workspace:. doesn't provide @arcgis/core (pcd5cf), requested by deck.gl.
➤ YN0002: │ deck-editable-test@workspace:. doesn't provide @deck.gl/core (pc2aa2), requested by @deck.gl-community/editable-layers.
➤ YN0002: │ deck-editable-test@workspace:. doesn't provide @deck.gl/extensions (p99524), requested by @deck.gl-community/editable-layers.
➤ YN0002: │ deck-editable-test@workspace:. doesn't provide @deck.gl/geo-layers (pd3205), requested by @deck.gl-community/editable-layers.
➤ YN0002: │ deck-editable-test@workspace:. doesn't provide @deck.gl/layers (p7250c), requested by @deck.gl-community/editable-layers.
➤ YN0002: │ deck-editable-test@workspace:. doesn't provide @deck.gl/mesh-layers (pde5d6), requested by @deck.gl-community/editable-layers.
➤ YN0002: │ deck-editable-test@workspace:. doesn't provide @luma.gl/constants (pe53c6), requested by @deck.gl-community/editable-layers.
➤ YN0002: │ deck-editable-test@workspace:. doesn't provide @luma.gl/core (pa844e), requested by @deck.gl-community/editable-layers and other dependencies.
➤ YN0002: │ deck-editable-test@workspace:. doesn't provide @math.gl/core (pad503), requested by @deck.gl-community/editable-layers.
➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 5 packages were added to the project (+ 39.56 MiB).
➤ YN0000: └ Completed in 16s 212ms
➤ YN0000: ┌ Link step
➤ YN0007: │ @swc/core@npm:1.7.21 [ec484] must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 3s 215ms
➤ YN0000: · Done with warnings in 36s 126ms
```

**Comment by ibgreen** [comment]
@xinaesthete I suspect that this is because deck.gl uses peerDependencies which requires the application to list all required deck.gl modules in package.json. This is intended to avoid subtle behaviors where package managers install multiple versions of a module.

**Comment by ibgreen** [comment]
This is no longer a luma.gl issue, let's move to discussions tab for now.
