### ISSUE TITLE
luma.gl/gltf@9.0.24 breaks the Google 3DTiles rendering (ScenegraphLayer No value for binding u_BaseColorSampler)

### ISSUE THREAD

**Issue by vsigno** [visgl/luma.gl#2233]
#### Actual Result
Using the latest release of `deck.gl@9.0.27`, the dependency `@luma.gl/gltf@9.0.24` (and onwards, up to `@luma.gl/gltf@9.0.26`) breaks the rendering of the Google 3DTiles (tiles are not displayed). Error: `deck.js:82  deck: drawing ScenegraphLayer No value for binding u_BaseColorSampler`.

Complete Error:
```console.error
deck: drawing ScenegraphLayer({id: 'tiles-scenegraph-https://tile.googleapis.com/v1/3dtiles/datasets/CgA/files/[....].glb'}) to screen: No value for binding u_BaseColorSampler in tiles-scenegraph-https://tile.googleapis.com/v1/3dtiles/datasets/CgA/files/[...].glb-cached Error: No value for binding u_BaseColorSampler in tiles-scenegraph-https://tile.googleapis.com/v1/3dtiles/datasets/CgA/files/[...].glb-cached
    at WEBGLRenderPipeline._applyBindings (webgl-render-pipeline.js:314:23)
    at WEBGLRenderPipeline.draw (webgl-render-pipeline.js:167:14)
    at _Model.draw (model.js:256:41)
    at scenegraph-layer.js:238:23
    at _GroupNode.traverse (group-node.js:80:17)
    at _GroupNode.traverse (group-node.js:77:23)
    at _GroupNode.traverse (group-node.js:77:23)
    at _ScenegraphLayer.draw (scenegraph-layer.js:223:31)
    at layer.js:851:22
    at withGLParameters (with-parameters.js:26:17)
```
#### Expected Result
Revert the dependency `@luma.gl/gltf@9.0.24` to `@luma.gl/gltf@9.0.23` solves the issue and the 3DTiles are displayed as expected

**Comment by chunlampang** [comment]
Not only the Google tile, all MeshLayer ScenegraphLayer are broken.

**Comment by ibgreen** [comment]
@felixpalmer This is likely due to the fact that luma.gl 9.0.23 included the UBO changes to the PBR module. Is there a deck.gl 9.0 patch that covers this?

**Comment by chunlampang** [comment]
> @felixpalmer This is likely due to the fact that luma.gl 9.0.23 included the UBO changes to the PBR module. Is there a deck.gl 9.0 patch that covers this?

Deckgl latest version from yesterday still using luma 9.0.15

**Comment by felixpalmer** [comment]
This the [breaking change](https://github.com/visgl/luma.gl/pull/2173/files#diff-a57d49d5e9016fa6a40bebe33d717bee5f7c47cfcf6d9e3b5023cb253216d4daL103). Unlike the lighting module PRs which were constrained to shader code in modules that deck@9.0 isn't using, the change to `createGLTFModel()` means that deck is pulling in the new UBO-based modules

As deck.gl@9.0 isn't including the UBO changes (that will come in deck@9.1) I would propose we revert https://github.com/visgl/luma.gl/pull/2173 and publish a new luma@9.0 version, @ibgreen do you agree? I think this is safer than patching deck@9.0

**Comment by ibgreen** [comment]
Agreed.

**Comment by felixpalmer** [comment]
@chunlampang @vsigno [9.0.27](https://www.npmjs.com/package/@luma.gl/gltf/v/9.0.27) should fix the issue, can you confirm?

**Comment by vsigno** [comment]
Yes, `@luma.gl/gltf@9.0.27` fixes the issue with the `Tile3DLayer`. I did also a quick test with a `ScenegraphLayer` and it looks fine. All models loaded with no errors.
