### ISSUE TITLE
Feature Request: support "strict" typescript settings in luma.gl

### ISSUE THREAD

**Issue by ccreed1988** [visgl/luma.gl#2241]
Some of the typings in resource.ts and shader-inputs.ts are incorrect. 

I noticed that the types in resource.ts have already been corrected in the master branch but it has not yet been released on a release branch. So I wanted to make this PR to fix what I saw in the shader-inputs.ts file.

I was unable to build my Angular project without this change.

I come across the issues in luma when trying to use the deck.gl library. I created a discussion about it on the deck.gl github page: https://github.com/visgl/deck.gl/discussions/9109

**Comment by ibgreen** [comment]
@ccreed1988 My understanding this was due to strict setting in the app. We have been working towards enabling strict mode in luma.gl but we are not there quite yet. I will rename this bug accordingly.
