### ISSUE TITLE
How to use the copyData function in luma8 Buffer object in luma9? 

### ISSUE THREAD

**Issue by tangzijun** [visgl/luma.gl#2260]
This function is removed in luma9. How can I use the alternative function?

**Comment by ibgreen** [comment]
Hi to make it possible to define an API that is portable between WebGPU and WebGL this was moved to the `CommandEncoder`

Something like 
```ts
const commandEncoder= device.createCommandEncoder();
commandEncoder.copyBufferToBuffer(...);
commandEncoder.finish();
```

We probably need to do a doc pass on that, but I think this should get you started.

**Comment by ibgreen** [comment]
For repo hygiene purposes we reserve issues for confirmed bugs, instead we use the github discussions tab for this kind of discourse, so closing this ticket but you are welcome to continue in discussions.

**Comment by tangzijun** [comment]
Thank you very much for your answer, that's great
