### ISSUE TITLE
[Bug] requestAdapterInfo not supported

### ISSUE THREAD

**Issue by felixpalmer** [visgl/luma.gl#2292]
### Description

When using [luma.gl](http://luma.gl/) 9.0.27, const adapterInfo = await adapter.requestAdapterInfo(); the funtion requestAdapterInfo is not defined.
And I found that this requestAdapterInfo is deprecated function and chrome does not support it anymore?

We have the [correct code](https://github.com/visgl/luma.gl/blob/cde11a2f2bda1542c77b0cbaa9cf6b66ef8597a2/modules/webgpu/src/adapter/webgpu-adapter.ts#L48) on master, but need to backport to 9.0 & 9.1

### Environment

- Framework version: 9.0.27
- Browser:
- Node:
- OS:

**Comment by ibgreen** [comment]
@felixpalmer Backporting landed on both branches, publishing would be the next step.
