### ISSUE TITLE
Framebuffer: improve handling of drawBuffers 

### ISSUE THREAD

**Issue by 1chandu** [visgl/luma.gl#322]
- [ ] Constructor sets `this.drawBuffers` to `[GL_COLOR_ATTACHMENT0]`, what if framebuffer's color attachment is bound to same buffer, doesn't it cause an issue? Also `this.drawBuffers` is not used any where, `clear` takes `drawBuffer` argument.
- [ ] `_setDrawBuffers` calls crashes when `drawBuffer` argument is passed to constructor. Some of the code inside this method need to be handled by `polyfill`.

**FIXED**
- [x] Several methods bind current framebuffer handle to `gl.FRAMEBUFFER` perform operations and then bind it to `null`,  (this.gl.bindFramebuffer(GL_FRAMEBUFFER, null)) instead we should actually set it to whatever that is was previously bound. Make `bindFramebuffer` to return cached value and use that handle instead of `null`.
- [x] `copyToTexture` method takes `srcFramebuffer`, shouldn't we just use `this.handle` and not pass any Framebuffer object.

**Comment by ibgreen** [comment]
- Constructor sets `this.drawBuffers` to `[GL_COLOR_ATTACHMENT0]`, what if framebuffer's color attachment is bound to same buffer, doesn't it cause an issue? Also `this.drawBuffers` is not used any where, `clear` takes `drawBuffer` argument.
- `_setDrawBuffers` calls crashes when `drawBuffer` argument is passed to constructor. Some of the code inside this method need to be handled by `polyfill`.

There may well be issues with `drawBuffers` implementation, and we really need a working example to demonstrate that the API is solid. Before making changes, be aware that the WebGL drawbuffers API (support for multiple render targets) contains a number of surprises, it took me a while to read up and digest it. When you are up to speed on it, we can sync and compare notes.

>  `copyToTexture` method takes `srcFramebuffer`, shouldn't we just use `this.handle` and not pass any Framebuffer object.

Agreed. I think it would be OK to change this in a patch release as it is clearly a bug in the API spec.
We can check for the srcFramebuffer parameter and show a warning if we detect it.

**Comment by tsherif** [comment]
@1chandu @ibgreen Are these still issues?

**Comment by 1chandu** [comment]
The remaining items are mostly cleanup and can be resolved when we support multiple draw buffers.
