### ISSUE TITLE
API enhancements for drawMode/vertexCount 

### ISSUE THREAD

**Issue by 1chandu** [visgl/luma.gl#392]
Based on comments from @ibgreen in #391 

In current luma.gl , `drawMode` and `vertexCount` can be specified by passing `Geometry` object or by passing them directly. We should explore the option of specifying these using `VertexArray` and `TransformFeedback` objects. Values passed to Model directly take precedence.

Should we drop the option of passing them through `Geometry` object? If no, we need to decide which one takes precedence (`Geometry` or` VertexArray`).

**Comment by tsherif** [comment]
@ibgreen @1chandu do we still feel this is relevant?

**Comment by ibgreen** [comment]
I don't have all the details fresh but there was a sense that the app has to do more book-keeping than is necessary when using the Transform class.

As an idea I think we could close this if we moved it to a tracker for Transform API improvements. I think the Transform class should start to be used more widely and we will likely want to make multiple improvements...
