### ISSUE TITLE
Jagged Edges when drawing polygons

### ISSUE THREAD

**Issue by CraigglesO** [visgl/luma.gl#565]
My first attempt discussing with deck.gl devs here:
https://github.com/uber/deck.gl/issues/1630

But deck is built ontop of luma, I realized this might be more of an issue that you guys can point me in the right direction.

What I see:
![alt-1](https://cdn.pbrd.co/images/Hf2b6yQ.png)
![alt-2](https://cdn.pbrd.co/images/Hf2bv7z.png)

What I get when using svg (too slow at scale):
![alt-3](https://cdn.pbrd.co/images/Hf2bSfM.png)

An example of the deck gl setup I used:
https://github.com/CraigglesO/isochrone-webgl-example

Just `yarn build && yarn start` and you are good to go.

Any thoughts about how I should approach webgl + luma to get the desired results I want?

Thanks,
Craig.

P.S.

Playing with three.js, it doesn't seem to hard to emulate svg styles with lines and polygons, just don't know how to implement using geojson with three.js

**Comment by tsherif** [comment]
@CraigglesO is this still an issue? If so can you post the images again as the links are broken.

**Comment by CraigglesO** [comment]
Hey, no problem. Sorry for not seeing this earlier,
I will post later today.

**Comment by CraigglesO** [comment]
@tsherif - here are the new images:

current luma:

<img width="729" alt="Screen Shot 2019-04-23 at 16 26 50" src="https://user-images.githubusercontent.com/5249140/56613672-1f62de00-65e5-11e9-9fd1-e3ea457d1779.png">

<img width="1094" alt="Screen Shot 2019-04-23 at 16 26 56" src="https://user-images.githubusercontent.com/5249140/56613692-2ab60980-65e5-11e9-9169-5d557b844e71.png">


rendering with svg's but slow:

<img width="774" alt="Screen Shot 2019-04-23 at 16 29 36" src="https://user-images.githubusercontent.com/5249140/56613706-330e4480-65e5-11e9-8d99-9926be8f472f.png">

<img width="1150" alt="Screen Shot 2019-04-23 at 16 30 06" src="https://user-images.githubusercontent.com/5249140/56613721-399cbc00-65e5-11e9-8574-355c97bf4dbb.png">


Do you think it's doable? I've even contacted mapbox about their drawing problem (not as severe but too noticeably messed up to utilize) and they never got around to it -_-
Would love to fix it myself if I had the time....

**Comment by CraigglesO** [comment]
Here is a gist of the isochrones if you want to use them as tests:
https://gist.github.com/CraigglesO/8ca3777bd816328b52ec397d98500662

**Comment by 1chandu** [comment]
@CraigglesO , my understanding is you are using deck.gl `PolygonLayer`, is that right? Or you are implementing you own layer using luma.gl API ? 

deck.gl offers, `ContourLayer` , [doc page](https://deck.gl/#/documentation/deckgl-api-reference/layers/contour-layer), does that work for your use case?
