### ISSUE TITLE
Make Transform Texture API official

### ISSUE THREAD

**Issue by 1chandu** [visgl/luma.gl#747]
#### Background 
In 6.2 we added Texture support for Transform as experimental, make this an official API

#### To Do List 
  - [x] Add label and assign to milestone 
  - [ ] Coding
      - [ ] Merge `sourceBuffers`, `_sourceTextures` into generic prop, like `inputs`.
      - [ ] Rename `feedbackBuffers` to `outputs` ? Check if `_targetTexture` can be merged into this.
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by tgorkin** [comment]
Related to #1193
