### ISSUE TITLE
Duplicated code between context-features and webgl-info

### ISSUE THREAD

**Issue by 1chandu** [visgl/luma.gl#797]
`/webgl-context/context-features.js` and `utils/webgl-info.js` has duplicated code. Internally platform-defines is using `webgl-info.j` but we are exporting some methods from `context-features.js`

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

**Comment by 1chandu** [comment]
This is a cleanup task, unless its causing any issues, we should only fix this in 7.1, too late for 7.0.

Moving to 7.1

**Comment by tsherif** [comment]
@1chandu is this duplicate of #1048?

**Comment by ibgreen** [comment]
Not related to `isWebGL`

**Comment by 1chandu** [comment]
Yeah, not same as #1048 , it refers to other code redundancy.
