### ISSUE TITLE
texture.setImageData and setSubImageData are do not work as expected

### ISSUE THREAD

**Issue by xintongxia** [visgl/luma.gl#831]
In order to make `texture.setImageData` and `texture.setSubImageData` functions work, `texture.generateMipmap()` has to be called after. 

Is it intended to be this? If so, should mention in documentation. But I think it makes more sense to do `generateMipmap()` inside `texture.setImageData` and `texture.setSubImageData`.

#### Reproduce Steps
I added a [debugging](https://github.com/uber/luma.gl/blob/xx/texture-debug/examples/wip/texture-display/app.js#L142) branch

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by ibgreen** [comment]
@xintongxia Good point.

Generating mipmaps is an optional step (depending on whether e.g. mipmap filtering is used), and there is certainly a cost associated with the generation, so we should probably not call it unconditionally every time the texture changes.

Let's say you need to do dozens of `texture.setSubImageData` calls to build e.g. a texture atlas. You don't want to regenerate mipmaps after every call, but only after the last call.

As for solutions:

* As a first step, updating the docs to specify which functions invalidate mipmaps sounds useful.

* One solution could be to maintain a `mipmapsDirty` flag on each texture, and then auto rebuild mipmaps just before use (only if the sampler used specifies MIPMAP based filtering).

**Comment by 1chandu** [comment]
Another related issue I found while debugging this with @xintongxia , we have two sources of truth for mipmap usage `1. filter setting`, `2. parameters.mipmap`.  Problem should also go away if you force non mipmap filtering in that debugging branch. User might set mipmaps to false, but not sure that default filter setting uses mipmaps.

So, either we should remove `parameters.mipmaps` or overwrite `filter` settings based on `parameters.mipmaps`.

**Comment by ibgreen** [comment]
Yes great point, though it gets a little trickier in WebGL2 where one texture can have multiple samplers with different filters, some might require mipmaps and others not.

I do think it is possible to detect whether mipmaps need to be regenerated before a draw call by inspecting supplied textures and samplers, assuming that the code sets the dirty flag appropriately.

But it is a bit of book-keeping, not yet fully convinced that the cost vs. value is justified.

**Comment by tsherif** [comment]
I don't think mipmaps should be an option. They should always be generated if the filtering requires it.
